# Generated by Django 4.1.2 on 2022-11-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_item_date_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='budget_code',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='financial_year',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
