# Generated by Django 4.1.2 on 2022-11-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_request_accepted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-request_created']},
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Request_Created',
            new_name='request_created',
        ),
    ]
