# Generated by Django 4.1.2 on 2022-11-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_created',
            field=models.DateField(editable=False),
        ),
    ]
