# Generated by Django 4.1.2 on 2022-11-25 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_request_request_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
