# Generated by Django 4.1.2 on 2022-11-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_request_rejected_request_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='remarks',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
