# Generated by Django 4.1.2 on 2022-11-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_request_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_for',
            field=models.CharField(max_length=256),
        ),
    ]
