# Generated by Django 4.1.2 on 2022-11-27 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_request_requested_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
