# Generated by Django 4.1.2 on 2022-12-18 04:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, max_length=264, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=264, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=264, null=True)),
                ('voucher_number', models.CharField(blank=True, max_length=264, null=True)),
                ('seller_info', models.TextField(blank=True, null=True)),
                ('date_of_purchase', models.DateField(blank=True, null=True)),
                ('unit_price', models.FloatField()),
                ('total_purchased', models.IntegerField()),
                ('in_stock', models.IntegerField()),
                ('warrenty', models.FloatField(blank=True, null=True)),
                ('budget_code', models.CharField(blank=True, max_length=264, null=True)),
                ('budget_title', models.CharField(blank=True, max_length=264, null=True)),
                ('financial_year', models.CharField(blank=True, max_length=264, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Request2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_for', models.CharField(choices=[('Other', 'Other'), ('CE', 'CE'), ('ARCH', 'ARCH'), ('PME', 'PME'), ('CSE', 'CSE'), ('EECE', 'EECE'), ('CE', 'CE'), ('ME', 'ME'), ('AE', 'AE'), ('NAME', 'NAME'), ('IPE', 'IPE'), ('NSE', 'NSE'), ('BME', 'BME'), ('SH', 'SH'), ('Office of The Commandant', 'Office of The Commandant'), ('MIST Secretariat', 'MIST Secretariat'), ('Academic Wing', 'Academic Wing'), ('Administration Wing', 'Administration Wing'), ('Research & Development Wing', 'Research & Development Wing'), ('Directorate of Student Welfare', 'Directorate of Student Welfare'), ('Directorate of Information and Communication Technology', 'Directorate of Information and Communication Technology'), ('Office of the Controller of Examination', 'Office of the Controller of Examination')], max_length=256)),
                ('additional_info', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.IntegerField()),
                ('request_created', models.DateTimeField(default=datetime.datetime.now)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_by', models.CharField(blank=True, max_length=256, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_by', models.CharField(blank=True, max_length=256, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product2.item2')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_created'],
            },
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Category', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='item2',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product2.product_info'),
        ),
        migrations.AddField(
            model_name='item2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
